/** @type {import('tailwindcss').Config} */
/* Design tokens from Stitch export — Kosovo Business Ledger ERP / Pristina Finance Core */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#49607c',
        'surface-container-low': '#edf4ff',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#2c4964',
        'inverse-on-surface': '#e8f2ff',
        primary: '#00152a',
        'on-secondary-container': '#45627e',
        'secondary-container': '#bfddfe',
        'tertiary-container': '#212a31',
        'primary-fixed': '#d1e4ff',
        'surface-container-high': '#d8eaff',
        tertiary: '#0d151c',
        'on-error': '#ffffff',
        'surface-bright': '#f7f9ff',
        'secondary-fixed': '#cee5ff',
        'on-primary-container': '#7a92b0',
        'outline-variant': '#c3c6ce',
        'on-tertiary': '#ffffff',
        'surface-variant': '#cee5ff',
        'tertiary-fixed-dim': '#bec7d1',
        'on-tertiary-container': '#88919a',
        'on-surface': '#001d32',
        'surface-container-highest': '#cee5ff',
        surface: '#f7f9ff',
        outline: '#74777e',
        'surface-container': '#e3efff',
        'tertiary-fixed': '#dae3ed',
        background: '#f7f9ff',
        'secondary-fixed-dim': '#accaea',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#3f4850',
        'inverse-surface': '#16334a',
        'on-background': '#001d32',
        'primary-container': '#102a43',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        'inverse-primary': '#b0c9e8',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#011d35',
        'on-primary-fixed-variant': '#314863',
        'on-tertiary-fixed': '#141d24',
        'on-surface-variant': '#43474d',
        secondary: '#44617d',
        'on-secondary-fixed': '#001d33',
        'surface-dim': '#c1ddfb',
        'primary-fixed-dim': '#b0c9e8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1440px',
        margin: '24px',
        'table-cell-padding-x': '12px',
        'table-cell-padding-y': '8px',
        unit: '4px',
        gutter: '16px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'label-caps': ['Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['"Public Sans"', 'system-ui', 'sans-serif'],
        'data-mono': ['Inter', 'ui-monospace', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['"Public Sans"', 'system-ui', 'sans-serif'],
        'body-md': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'label-caps': [
          '11px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' },
        ],
        'headline-lg': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'data-mono': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
