apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guri-finance-ingress
  namespace: guri-finance
spec:
  ingressClassName: nginx
  rules:
    - host: guri.finance
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

